from collections import Counter

class Solution:
    """
    Task:
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.
    """
    def findTheDifference(self, s: str, t: str) -> str:
        t = Counter(t)
        for w in s:
            t[w] -= 1
        return max(t, key=t.get)